### ISSUE TITLE
searchatthetable url

### ISSUE THREAD

**Issue by kavita-p** [kore-signet/memorious#1]
hi! wanted to ask about the old searchatthetable.com url, which currently seems to redirect to curiosity.cat-girl.gay instead of  memorious.cat-girl.gay. is that something you plan to update? it'd be cool to know for the wiki's sake as well as having something to point people to easily

**Comment by kore-signet** [comment]
Hi! I  don't control searchatthetable.com, but I can say that curiosity.cat-girl.gay is being updated! I'm putting finishing touches on the new version; hopefully it'll be out by end of this week.

**Comment by kore-signet** [comment]
It's now back! :D
